ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/ViewModels/DictionaryViewModel.cs
using ForeignWordsTrainer.Models.LearnModels;

namespace ForeignWordsTrainer.ViewModels
{
    public class DictionaryViewModel
    {
        public string SearchTerm { get; set; }

        public WordModel WordInformation { get; set; }

        public LearnUserModel LearnUser { get; set; }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/ViewModels/TrainWordViewModel.cs
using ForeignWordsTrainer.Models.LearnModels;

namespace ForeignWordsTrainer.ViewModels
{
    public class TrainWordViewModel
    {
        public List<WordModel> Words { get; set; }
        public List<WordModel> SelectedWords {  get; set; }
        public LearnUserModel LearnUser { get; set; }

    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Controllers/LearnControllers/DictionaryController.cs
using ForeignWordsTrainer.Data;
using ForeignWordsTrainer.Data.WordsLearningDb.Models;
using ForeignWordsTrainer.Models.LearnModels;
using ForeignWordsTrainer.Services;
using ForeignWordsTrainer.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ForeignWordsTrainer.Controllers.LearnControllers
{
    [Authorize("role")]
    [Route("api/[controller]")]
    [ApiController]
    public class DictionaryController : Controller
    {
        private readonly WordsLearningDbContext _dbContext;
        private readonly Dictionary<string, WordDalModel> _wordDalModelDictionary;
        private readonly WordService _wordService;
        private readonly WordMappingService _wordMappingService;
        private readonly UserWordsService _userWordsService;
        private string UserId => GetUserId();

        public DictionaryController(WordsLearningDbContext dbContext, WordService wordService, 
            WordMappingService wordMappingService, UserWordsService userWordsService)
        {
            _dbContext = dbContext;
            _wordService = wordService;
            _wordDalModelDictionary = LoadWordsIntoDictionary();
            _wordMappingService = wordMappingService;
            _userWordsService = userWordsService;
        }
        private string GetUserId()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return userId;
        }

        [HttpPost("Search")]
        public IActionResult Search([FromForm]string searchTerm = "")
        {
            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                var viewModel = new DictionaryViewModel
                {
                    SearchTerm = searchTerm,
                    WordInformation = new WordModel(),
                    LearnUser = _userWordsService.GetUserWords(UserId)
                };
                return View("~/Views/Learn/Dictionary.cshtml", viewModel);
            }

            searchTerm = searchTerm.ToLower();

            if (_wordDalModelDictionary.ContainsKey(searchTerm))
            {
                var wordDalModel = _wordDalModelDictionary[searchTerm];
                var wordModel = _wordMappingService.MapToWordModel(wordDalModel);

                var viewModel = new DictionaryViewModel
                {
                    SearchTerm = searchTerm,
                    WordInformation = wordModel,
                    LearnUser = _userWordsService.GetUserWords(UserId)
                };

                return View("~/Views/Learn/Dictionary.cshtml", viewModel);
            }
            else
            {
                var viewModel = new DictionaryViewModel
                {
                    SearchTerm = searchTerm,
                    WordInformation = new WordModel(),
                    LearnUser = _userWordsService.GetUserWords(UserId)
                };
                return View("~/Views/Learn/Dictionary.cshtml", viewModel);
            }
        }

        [HttpPost("ProcessAddWordToUserDictionary")]
        public IActionResult ProcessAddWordToUserDictionary([FromForm] WordModel wordModel)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View("YourOriginalView", wordModel); TODO: adjust later
            //}

            //if (string.IsNullOrWhiteSpace(searchTerm))
            //{
            //    var viewModel = new DictionaryViewModel
            //    {
            //        SearchTerm = searchTerm,
            //        WordInformation = new WordModel(),
            //        LearnUser = _userWordsService.GetUserWords(UserId)
            //    };
            //    return View("~/Views/Learn/Dictionary.cshtml", viewModel);
            //}

            var userId = UserId;
            var dalModel = _wordMappingService.MapToWordDalModel(wordModel);

            var wordAddingStatus = _userWordsService.AddWordToUserDictionary(userId, dalModel);

            if (wordAddingStatus.Success)
            {
                return RedirectToAction("Dictionary", "Dictionary");
            }
            else
            {
                if (wordAddingStatus.Message == "User not found")
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (wordAddingStatus.Message == "Word is already in user's dictionary")
                {
                    return RedirectToAction("Dictionary", "Dictionary");
                }
                else
                {
                    return View("Error", wordAddingStatus);
                }
            }
        }

        [HttpPost("ProcessRemoveWordFromUserDictionary")]
        public IActionResult ProcessRemoveWordFromUserDictionary([FromForm] WordModel wordModel)
        {
            var userId = UserId;
            var dalModel = _wordMappingService.MapToWordDalModel(wordModel);

            var wordRemovingStatus = _userWordsService.DeleteWordFromUserDictionary(userId, dalModel);

            if (wordRemovingStatus.Success)
            {
                return RedirectToAction("Dictionary", "Dictionary");
            }
            else
            {
                if (wordRemovingStatus.Message == "User not found")
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (wordRemovingStatus.Message == "Word not found in user's dictionary")
                {
                    return RedirectToAction("Dictionary", "Dictionary");
                }
                else
                {
                    return View("Error");
                }
            }
        }

        private Dictionary<string, WordDalModel> LoadWordsIntoDictionary()
        {
            var wordsFromDb = _wordService.GetAllWordsFromDatabase();

            var dalWordsDictionary = wordsFromDb.ToDictionary(wm => wm.Word, wm => wm);

            return dalWordsDictionary;
        }

        [HttpGet("Dictionary")]
        public IActionResult Dictionary()
        {
            var viewModel = new DictionaryViewModel
            {
                SearchTerm = default!,
                WordInformation = new WordModel(),
                LearnUser = _userWordsService.GetUserWords(UserId),
            };

            return View("~/Views/Learn/Dictionary.cshtml", viewModel);
        }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Controllers/LearnControllers/LearnController.cs
using ForeignWordsTrainer.Data;
using ForeignWordsTrainer.Data.AuthSystemDb;
using ForeignWordsTrainer.Data.WordsLearningDb.Models;
using ForeignWordsTrainer.Models.LearnModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;

namespace ForeignWordsTrainer.Controllers.LearnControllers
{
    [Authorize("role")]
    [Route("api/[controller]")]
    [ApiController]
    public class LearnController : Controller
    {
        private readonly WordsLearningDbContext _dbContext;
        private readonly UserManager<AuthUser> _userManager;

        public LearnController(WordsLearningDbContext context, UserManager<AuthUser> userManager)
        {
            _dbContext = context;
            _userManager = userManager;
        }
        public IActionResult Dictionary()
        {
            ViewData["Title"] = "Log in";
            return View("~/Views/Learn/Dictionary.cshtml");
        }

        [HttpGet]
        public IActionResult GetWords()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            UserDalModel dalUser = null;
            LearnUserModel learnUser = null;

            if (userId != null)
            {
                dalUser = _dbContext.UsersList.Include(u => u.Words).SingleOrDefault(u => u.Id == userId);

                if (dalUser != null && dalUser.Words != null && dalUser.Words.Any())
                {
                    var wordsWithTranslations = dalUser.Words.Select(uw => new WordModel
                    {
                        Word = uw.Word,
                        TranslUkr = uw.TranslUkr,
                        TranslRus = uw.TranslRus
                    }).ToList();

                    learnUser = new LearnUserModel()
                    {
                        Name = dalUser.Name,
                        Words = wordsWithTranslations
                    };
                }
                else
                {
                    return Ok($"{dalUser.Name}'s dictionary is empty.");
                }
            }
            return View("~/Views/Learn/Dictionary.cshtml", learnUser);
        }
        public IActionResult Exercise1()
        {
            return View();
        }
        public IActionResult Exercise2()
        {
            return View();
        }
        public IActionResult Exercise3()
        {
            return View();
        }
        public IActionResult Exercise4()
        {
            return View();
        }
        public IActionResult Exercise5()
        {
            return View();
        }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Controllers/LearnControllers/TrainWordController.cs
using ForeignWordsTrainer.Models.LearnModels;
using ForeignWordsTrainer.Services;
using ForeignWordsTrainer.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ForeignWordsTrainer.Controllers.LearnControllers
{
    [Authorize("role")]
    [Route("api/[controller]")]
    [ApiController]
    public class TrainWordController : Controller
    {
        private readonly WordService _wordService;
        private readonly UserWordsService _userWordsService;
        private readonly WordMappingService _wordMappingService;
        private string UserId => GetUserId();

        private static List<WordModel> selectedWords = new List<WordModel>();

        public TrainWordController(WordService wordService, UserWordsService userWordsService,
            WordMappingService wordMappingService)
        {
            _wordService = wordService;
            _userWordsService = userWordsService;
            _wordMappingService = wordMappingService;
        }
        private string GetUserId()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return userId;
        }

        [HttpGet("Train")]
        public IActionResult Train()
        {
            var viewModel = new TrainWordViewModel
            {
                Words = _wordMappingService.MapToWordModel(_wordService.GetAllWordsFromDatabase()),
                SelectedWords = new List<WordModel>(),
                LearnUser = _userWordsService.GetUserWords(UserId)
            };

            return View("~/Views/Learn/TrainWord.cshtml", viewModel);
        }
        [HttpPost("AddToTrainList")]
        public IActionResult AddWordToTrainList([FromForm] WordModel selectedWord)
        {
            if (selectedWord != null || selectedWords.Contains(selectedWord))
            {
                return RedirectToAction("Train");
            }
            else
            {
                selectedWords.Add(selectedWord);
                return RedirectToAction("Train");
            }
        }

        [HttpPost("TrainWords")]
        public IActionResult TrainWords(IList<WordModel> selectedWords)
        {
            if (selectedWords == null || !selectedWords.Any())
            {
                return RedirectToAction("Train");
            }
            else
            {
                return RedirectToAction("TrainExersice");
            }

            // TODO: think where and how  clear the selectedWords collection
        }

        [HttpPost("AddWordsToDeck")]
        public ActionResult AddWordsToDeck(List<WordModel> selectedWords)
        {
            string[] selectedWords1 = Request.Form["selectedWords"]; // Get selected words from the form
                                                                    // Logic to add selected words to the user's flashcard deck (e.g., store in a database or session)
            return View(); // Redirect or return a success message
        }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Views/Learn/Dictionary.cshtml
@model ForeignWordsTrainer.ViewModels.DictionaryViewModel

@{
    ViewData["Title"] = "Dictionary";
}

<h1>My dictionary</h1>

<div class="container mt-4">

    <form method="post" asp-action="Search" asp-controller="Dictionary" novalidate>
        <div class="form-group">
            <label for="searchTerm">Search Term:</label>
            <input type="text" id="searchTerm" name="SearchTerm" class="form-control" required />
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <div>
        <h3>Word Information</h3>

        @if (Model.WordInformation.WordId != 0)
        {
            <p>@Model.WordInformation.Word - @Model.WordInformation.TranslUkr</p>

            <form method="post" asp-action="ProcessAddWordToUserDictionary" asp-controller="Dictionary">
                <input type="hidden" name="WordId" value="@Model.WordInformation.WordId" />
                <input type="hidden" name="Word" value="@Model.WordInformation.Word" />
                <input type="hidden" name="TranslUkr" value="@Model.WordInformation.TranslUkr" />
                <input type="hidden" name="TranslRus" value="@Model.WordInformation.TranslRus" />

                <button type="submit" class="btn btn-primary">Add to Dictionary</button>
            </form>
        }
        else
        {
            <button type="button" class="btn btn-primary" disabled>Add to Dictionary</button>
        }
    </div>

    @if (Model.LearnUser.Words != null && Model.LearnUser.Words.Any())
    {
        <p>Here are words from your dictionary. To delete word from your dictionary just click on it.</p>
        <div class="d-flex justify-content-left">
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                @foreach (var element in Model.LearnUser.Words)
                {
                    <form method="post" asp-action="ProcessRemoveWordFromUserDictionary" asp-controller="Dictionary">
                        <input type="hidden" name="WordId" value="@element.WordId" />
                        <input type="hidden" name="Word" value="@element.Word" />
                        <input type="hidden" name="TranslUkr" value="@element.TranslUkr" />
                        <input type="hidden" name="TranslRus" value="@element.TranslRus" />

                        <button type="submit" class="btn btn-primary">@element.Word</button>
                    </form>
                }
            </div>
        </div>
    }
    else
    {
        <div>
            <p>Your dictionary is empty. Start adding words to learn!</p>
        </div>
    }

    <div class="d-flex justify-content-center mt-4">
        <a class="btn btn-lg btn-primary" asp-controller="TrainWord" asp-action="Train">Go to train page</a>
    </div>

</div>

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Views/Learn/TrainWord.cshtml
@model ForeignWordsTrainer.ViewModels.TrainWordViewModel

@{
    ViewData["Title"] = "Train";
}

<h1>Word trainer page</h1>

<p>Pick words you want to train by clicking them.</p>

<form asp-controller="TrainWord" asp-action="AddWordsToDeck" method="post">
    <table class="table">
        <thead>
            <tr>
                <th>Word</th>
                <th>Select</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.LearnUser.Words.Count; i++)
            {
                var element = Model.LearnUser.Words[i];
                <tr>
                    <td>@element.Word</td>
                    <td>
                        <input type="hidden" name="SelectedWords[@i].WordId" value="@element.WordId" />
                        <input type="hidden" name="SelectedWords[@i].Word" value="@element.Word" />
                        <input type="hidden" name="SelectedWords[@i].TranslUkr" value="@element.TranslUkr" />
                        <input type="hidden" name="SelectedWords[@i].TranslRus" value="@element.TranslRus" />
                        <input type="checkbox" name="SelectedWords[@i].IsSelected" value="true" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button type="submit" class="btn btn-primary">Add Selected Words to Deck</button>
</form>

<div class="container">
    <div class="d-flex justify-content-between mt-4">
        <form method="post" asp-action="TrainSelectedWords" asp-controller="TrainWord">
            <button type="submit" class="btn btn-lg btn-primary">Train Selected Words</button>
        </form>
        <form method="post" asp-action="TrainAllWords" asp-controller="TrainWord">
            <button type="submit" class="btn btn-lg btn-primary">Train All Words</button>
        </form>
    </div>
</div>