ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Controllers/AuthControllers/LoginController.cs
using ForeignWordsTrainer.Data.AuthSystemDb;
using ForeignWordsTrainer.Models.AuthModels;
using ForeignWordsTrainer.Utils.AuthJwt;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForeignWordsTrainer.Controllers.AuthControllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LoginController : Controller
    {
        private readonly JwtTokenGenerator _jwtTokenGenerator;
        private readonly UserManager<AuthUser> _userManager;

        public LoginController(JwtTokenGenerator jwtTokenGenerator,
            UserManager<AuthUser> userManager) 
        {
            _jwtTokenGenerator = jwtTokenGenerator;
            _userManager = userManager; 
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {
            ViewData["Title"] = "Log in";
            return View("~/Views/Account/Login.cshtml");
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login([FromForm] LoginUserModel loginModel) 
        {
            var user = await _userManager.FindByNameAsync(loginModel.Email);

            if (user != null)
            {
                var isPasswordValid = await _userManager.CheckPasswordAsync(user, loginModel.Password);

                if (isPasswordValid)
                {
                    var token = _jwtTokenGenerator.GenerateJwtToken(user);

                    Response.Cookies.Append("X-Access-Token", token, new CookieOptions() { HttpOnly = true, SameSite = SameSiteMode.Strict, Secure = true });

                    return RedirectToAction("Dictionary", "Dictionary");
                }
            }

            ViewData["ErrorMessage"] = "Invalid email or password.";

            return View("~/Views/Account/Login.cshtml");
        }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Controllers/AuthControllers/LogoutController.cs
using ForeignWordsTrainer.Models.AuthModels;
using ForeignWordsTrainer.Utils.AuthJwt;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace ForeignWordsTrainer.Controllers.AuthControllers
{
    //[Authorize("role")]
    [Route("api/[controller]")]
    [ApiController]
    public class LogoutController : Controller
    {
        
        [HttpGet]
        public IActionResult Logout()
        {
            //await HttpContext.SignOutAsync(JwtBearerDefaults.AuthenticationScheme);
            Response.Cookies.Delete("X-Access-Token");
            return RedirectToAction("Index", "Home");
        }
    }
}

ForeignWordsTrainer/ForeignWordsTrainer/ForeignWordsTrainer/Views/Shared/_Layout.cshtml
@using ForeignWordsTrainer.Models.AuthModels;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForeignWordsTrainer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ForeignWordsTrainer.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ForeignWordsTrainer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <span class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="button btn btn-secondary" asp-area="" asp-controller="Logout" asp-action="Logout">Sign out here!</a>
                        }
                        else
                        {
                            <a class="button btn btn-primary" asp-area="" asp-controller="Login" asp-action="Login">Get started!</a>
                        }
                    </span>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark" data-bs-theme="dark">
        <div class="container">
            &copy; 2023 - ForeignWordsTrainer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>